config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "public/homes#top"
  get 'public/homes/about' => 'public/homes#about', as: 'about'
  
  # ユーザ用
  # URL /users/sign_in ...
  devise_for :users ,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index,:show,:edit,:update]
    
    resources :posts, only: [:index,:show,:destroy]
  end
  
  namespace :public do
    resources :users, only: [:show,:edit,:update]
    
    resources :posts, except: [:edit] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
       get 'search'
       get 'rank'
      end
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  #Categoriesテーブルから中間テーブルに対する関連付け
  has_many :post_category_relations, dependent: :destroy
  #Categoriesテーブルから中間テーブルを介してPostテーブルへの関連付け
  has_many :posts, through: :post_category_relations, dependent: :destroy
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/jenre.rb
class Jenre < ApplicationRecord
  
  #Jenresテーブルから中間テーブルに対する関連付け
  has_many :post_jenre_relations, dependent: :destroy
  #Jenresテーブルから中間テーブルを介してPostテーブルへの関連付け
  has_many :posts, through: :post_jenre_relations, dependent: :destroy
  
end

app/models/place.rb
class Place < ApplicationRecord
  
  #Placesテーブルから中間テーブルに対する関連付け
  has_many :post_place_relations, dependent: :destroy
  #Placesテーブルから中間テーブルを介してPostテーブルへの関連付け
  has_many :posts, through: :post_place_relations, dependent: :destroy
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # jenreテーブルへの関連付け
  has_many :post_jenre_relations, dependent: :destroy
  has_many :jenres, through: :post_jenre_relations, dependent: :destroy
  
   # placeテーブルへの関連付け
  has_many :post_place_relations, dependent: :destroy
  has_many :places, through: :post_place_relations, dependent: :destroy
  
   # categoryテーブルへの関連付け
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations, dependent: :destroy
  
  validates :title,presence:true
  validates :body, presence:true,length:{maximum:200}
  validates :address, presence: true
  
  validates :all_rate, numericality: true
  validates :rush_rate, numericality: true
  validates :relax_rate, numericality: true
  validates :beautiful_rate, numericality: true
  
  has_many_attached :main_images
  
  def favorited_by?(user)
      favorites.exists?(user_id: user.id)
  end
  
  # キーワード検索
  def self.search(search) 
   if search != ""
     Post.where(['address LIKE(?) OR title LIKE(?)',"%#{search}%","%#{search}%"]) 
   else
     Post.all
   end
  end
  
  def self.create_favorite_ranks #postクラスからデータを取ってくる処理なのでクラスメソッド！
    Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end
  
  def self.create_comment_ranks 
    Post.find(PostComment.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end
  
 
  
end

app/models/post_category_relation.rb
class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  validates :comment,presence:true
  
end

app/models/post_jenre_relation.rb
class PostJenreRelation < ApplicationRecord
  belongs_to :post
  belongs_to :jenre
end

app/models/post_place_relation.rb
class PostPlaceRelation < ApplicationRecord
  belongs_to :post
  belongs_to :place
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length:{maximum:100}
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.png'
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path(@posts)
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
      flash[:notice] = '会員情報が更新されました。'
    else
      render :edit
      flash[:alert] = "会員情報が更新されませんでした"
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:introduction,:email,:is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_index.html.erb
<div class="row">
  <% posts.each do |post| %>
    <div class="col-12 col-md-3">
      <div class="post-index">
        <div class="card rounded">
          <div class="card-img-top bd-placeholder-img">
            <%= link_to admin_post_path(post.id) do %>
              <% if post.main_images.attached? %>
                <% post.main_images.first(1).each do |main_image| %>
                  <%= image_tag main_image.variant( resize: "600x500^", gravity: "center", crop: "600x500+0+0" ), class: "img-fluid rounded" %>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <div class="card-text">
              <!--タグ関連-->
            <div class="tag">
              <% post.places.each do |place| %>
               <span class="name-tag">#<%= place.name %></span>
              <% end %>
              <% post.jenres.each do |jenre| %>
               <span class="name-tag">#<%= jenre.name %></span>
              <% end %>
              <% post.categories.each do |category| %>
               <span class="name-tag">#<%= category.name %></span>
              <% end %>
            </div>
              <div id="star-all-rate<%= post.id%>">満足度：</div>
          </div>
      
          <script>
            $('#star-all-rate<%= post.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              starHalf  : '<%= asset_path('star-half.png') %>',
              readOnly: true,
              score: <%= post.all_rate %>,
            });
          </script> 
          </div>
        </div>
      </div>      
    </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<%= render 'admin/posts/index',posts: @posts %>

app/views/admin/posts/show.html.erb
<div class="row">
  <div class="col-6 offset-1">
    <div class="img-box">
      <div class="slider-show">
        <% if @post.main_images.attached? %>
          <% @post.main_images.each do |main_image| %>
            <%= image_tag main_image, class: "show-image" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-4 ml-2">
    <h2><%= @post.title %></h2>
    <div class="mt-2">所在地：<%= @post.address %></div>
    <div class="mt-2 d-flex">
      <%= link_to admin_user_path(@post.user) do %>
        <%= image_tag @post.user.get_profile_image,class: "post-profile-img" %>
        <%= @post.user.name %>
      <% end %>
      <div class="ml-3">
        <%= link_to "投稿を削除", public_post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' },class: "btn btn-outline-danger btn-sm" %>
      </div>
    </div>
        
        <!--タグ関連-->
    <div class="tag">
      <% @post.jenres.each do |jenre| %>
       <span class="name-tag">#<%= jenre.name %></span>
      <% end %>
      
      <% @post.places.each do |place| %>
       <span class="name-tag">#<%= place.name %></span>
      <% end %>
      
      <% @post.categories.each do |category| %>
       <span class="name-tag">#<%= category.name %></span>
      <% end %>
    </div>

    <h4 class="border-bottom mt-3">詳細</h4>   
    <div class="mt-1"><%= @post.body %></div>
    
    <!--レビュー機能-->
    <h4 class="border-bottom mt-3">評価</h4>
    <div class="mt-1" id="star-all-rate<%= @post.id%>">満足度：</div>
    <div class="mt-1" id="star-rush-rate<%= @post.id%>">混　雑：</div>
    <div class="mt-1" id="star-relax-rate<%= @post.id%>">安らぎ：</div>
    <div class="my-1" id="star-beautiful-rate<%= @post.id%>">綺麗さ：</div>

<!--コメント一覧-->
    <div id="comments-area mt-3">
     <%= render 'public/post_comments/post_comment', post: @post, post_comment: @post_comment %>
    </div>

  </div>
</div>


<!--レビュー機能JavaScript-->
 <script>
    $('#star-all-rate<%= @post.id%>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      starHalf  : '<%= asset_path('star-half.png') %>',
      readOnly: true,
      score: <%= @post.all_rate %>,
    });
     $('#star-rush-rate<%= @post.id%>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      starHalf  : '<%= asset_path('star-half.png') %>',
      readOnly: true,
      score: <%= @post.rush_rate %>,
    });
     $('#star-relax-rate<%= @post.id%>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      starHalf  : '<%= asset_path('star-half.png') %>',
      readOnly: true,
      score: <%= @post.relax_rate %>,
    });
     $('#star-beautiful-rate<%= @post.id%>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      starHalf  : '<%= asset_path('star-half.png') %>',
      readOnly: true,
      score: <%= @post.beautiful_rate %>,
    });
  </script>