config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "public/homes#top"
  get 'public/homes/about' => 'public/homes#about', as: 'about'
  
  # ユーザ用
  # URL /users/sign_in ...
  devise_for :users ,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index,:show,:edit,:update]
    
    resources :posts, only: [:index,:show,:destroy]
  end
  
  namespace :public do
    resources :users, only: [:show,:edit,:update]
    
    resources :posts, except: [:edit] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
       get 'search'
       get 'rank'
      end
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  #Categoriesテーブルから中間テーブルに対する関連付け
  has_many :post_category_relations, dependent: :destroy
  #Categoriesテーブルから中間テーブルを介してPostテーブルへの関連付け
  has_many :posts, through: :post_category_relations, dependent: :destroy
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/jenre.rb
class Jenre < ApplicationRecord
  
  #Jenresテーブルから中間テーブルに対する関連付け
  has_many :post_jenre_relations, dependent: :destroy
  #Jenresテーブルから中間テーブルを介してPostテーブルへの関連付け
  has_many :posts, through: :post_jenre_relations, dependent: :destroy
  
end

app/models/place.rb
class Place < ApplicationRecord
  
  #Placesテーブルから中間テーブルに対する関連付け
  has_many :post_place_relations, dependent: :destroy
  #Placesテーブルから中間テーブルを介してPostテーブルへの関連付け
  has_many :posts, through: :post_place_relations, dependent: :destroy
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # jenreテーブルへの関連付け
  has_many :post_jenre_relations, dependent: :destroy
  has_many :jenres, through: :post_jenre_relations, dependent: :destroy
  
   # placeテーブルへの関連付け
  has_many :post_place_relations, dependent: :destroy
  has_many :places, through: :post_place_relations, dependent: :destroy
  
   # categoryテーブルへの関連付け
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations, dependent: :destroy
  
  validates :title,presence:true
  validates :body, presence:true,length:{maximum:200}
  validates :address, presence: true
  
  validates :all_rate, numericality: true
  validates :rush_rate, numericality: true
  validates :relax_rate, numericality: true
  validates :beautiful_rate, numericality: true
  
  has_many_attached :main_images
  
  def favorited_by?(user)
      favorites.exists?(user_id: user.id)
  end
  
  # キーワード検索
  def self.search(search) 
   if search != ""
     Post.where(['address LIKE(?) OR title LIKE(?)',"%#{search}%","%#{search}%"]) 
   else
     Post.all
   end
  end
  
  def self.create_favorite_ranks #postクラスからデータを取ってくる処理なのでクラスメソッド！
    Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end
  
  def self.create_comment_ranks 
    Post.find(PostComment.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end
  
 
  
end

app/models/post_category_relation.rb
class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  validates :comment,presence:true
  
end

app/models/post_jenre_relation.rb
class PostJenreRelation < ApplicationRecord
  belongs_to :post
  belongs_to :jenre
end

app/models/post_place_relation.rb
class PostPlaceRelation < ApplicationRecord
  belongs_to :post
  belongs_to :place
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length:{maximum:100}
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.png'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p><small>CopyRight Yofukashi.inc</small></p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header-wapper">
    
    <h2>
      <%= link_to root_path,class: "top-icon",data: {"turbolinks" => false} do %>
       <i class="far fa-moon"></i>Yofukashi
      <% end %>
    </h2>
    <!--ユーザのヘッダー-->
    <% if user_signed_in? %>
      <nav>
        <ul class="text-nav">
          <li><%= link_to 'はじめに',about_path, class: "header-text"%></li>
          
          <li>
            <%= link_to public_user_path(current_user), class: "header-text" do %>
              <i class="fas fa-user"></i>マイページ
            <% end %>
          </li>
          
          <li>
            <%= link_to new_public_post_path, class: "header-text" do %>
              <i class="fas fa-edit"></i>投稿する
              <% end %>
          </li>
          
          <li>
            <%= link_to public_posts_path, class: "header-text" do %>
              <i class="fas fa-users"></i>みんなの投稿
            <% end %>
          </li>
          
          <li>
            <%= link_to rank_public_posts_path, class: "header-text" do %>
              <i class="fas fa-crown"></i>ランキング
            <% end %>
          </li>
          
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "header-text" do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
          
          <li>
            <%= link_to search_public_posts_path, class: "header-text" do %>
               <i class="fas fa-search"></i>検索
            <% end %>   
          </li>
        </ul>
      </nav>
    <!--アドミンのヘッダー-->
    <% elsif admin_signed_in? %>
      <nav>
        <ul class="text-nav">
           <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: "header-text" do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
          
          <li>
            <%= link_to admin_users_path, class: "header-text" do %>
              <i class="fas fa-users"></i>ユーザー一覧
            <% end %>
          </li>
          
          <li>
            <%= link_to admin_posts_path, class: "header-text" do %>
              <i class="fas fa-edit"></i>投稿一覧
              <% end %>
          </li>
        </ul>
      </nav>
    <!--ゲストのヘッダー-->
    <% else %>
      <nav>
        <ul class="text-nav">
          <li><%= link_to 'はじめに',about_path, class: "header-text"%></li>
          
          <li>
            <%= link_to new_user_session_path, class: "header-text" do %>
              <i class="fas fa-sign-in-alt"></i>ログイン
            <% end %>
          </li>
          
          <li>
            <%= link_to new_user_registration_path, class: "header-text" do %>
              <i class="fas fa-user-plus"></i>新規登録
            <% end %>
          </li>
        </ul>
      </nav>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yofukashi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
   

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <!--<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <!--adobe-font-->
    <script>
      (function(d) {
        var config = {
          kitId: 'npe6luu',
          scriptTimeout: 3000,
          async: true
        },
        h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
      })(document);
    </script>

  </head>

  <body>
    <!-- 'header'の部分テンプレート -->
    <%= render 'layouts/header' %>
    
    <%= yield %>
    
    <!-- 'footer'の部分テンプレート -->
      <%= render 'layouts/footer' %>
  </body>
</html>